### ISSUE TITLE
Max. Zones : 20 ---> need 56 ;-)

### ISSUE THREAD

**Issue by Adefx** [dnpwwo/Domoticz-DSCEnvisalink-Plugin#2]
Hi ! i'm using 56 zone on 2 partitions 
Is possible to add some more available zone ? at least 64

Thanks a lot

Edit i've forked the script to test... seems to work well with 8 partition & 64 zones.
Maybe it need some adjustment on the zone bypass offset thing

**Comment by dnpwwo** [comment]
As far as I know you could just add more entries to the "Max. Zones" drop down.

Do you have more detail on the bypass issue?  The code looks like it should work to me.

**Comment by Adefx** [comment]
Hi, 
Nope , the zone bypass work perfectly. 
I've added the zone & partition into a fork, if you want you could merge it in your code
